
<div class="content">
    <div class="left">
        <span>Linux Status</span>
        <ul>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'generalInfo'))?>">General Info</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'ram'))?>">Ram</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'diskUsage'))?>">Disk Usage</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'software'))?>">Software</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'users'));?>">Users</a></li>
            <li class="current"><a href="<?php echo $this->url('linuxstatus',array('action' => 'online'));?>">Online</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'lastLogin'));?>">Last Login</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'processes'));?>">Processes</a></li>
        </ul>
    </div>
    <div class="right">  
        <span>Information</span>
        <ul>
            <li class="li">
                <p class="l6">WHO</p>
                <p class="l8">TTY</p>
                <p class="l6">FROM</p>
                <p class="l6">LOGIN@</p>
                <p class="l6">IDLE</p>
                <p class="l8">JCPU</p>
                <p class="l8">PCPU</p>
            </li>
            <?php for($i=0;$i<count($result);$i++){?>
                <li class="li">
                    <p class="l6"><?php echo $result[$i][0];?></p>
                    <p class="l8"><?php echo $result[$i][1];?></p>
                    <?php if($result[$i][1]=="tty1"){?>
                    <p class="l6"><?php echo "-";?></p>
                    <p class="l6"><?php echo $result[$i][2];?></p>
                    <p class="l6"><?php echo $result[$i][3];?></p>
                    <p class="l8"><?php echo $result[$i][4];?></p>
                    <p class="l8"><?php echo $result[$i][5];?></p>
                    <?php }else{ ?>
                    <p class="l6"><?php echo $result[$i][2];?></p>
                    <p class="l6"><?php echo $result[$i][3];?></p>
                    <p class="l6"><?php echo $result[$i][4];?></p>
                    <p class="l8"><?php echo $result[$i][5];?></p>
                    <p class="l8"><?php echo $result[$i][6];?></p>
                    <?php } ?>
                </li>
            <?php }?>
    </div>
</div>