
<div class="content">
    <div class="left">
        <span>Linux Status</span>
        <ul>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'generalInfo'))?>">General Info</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'ram'))?>">Ram</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'diskUsage'))?>">Disk Usage</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'software'))?>">Software</a></li>
            <li class="current"><a href="<?php echo $this->url('linuxstatus',array('action' => 'users'));?>">Users</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'online'));?>">Online</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'lastLogin'));?>">Last Login</a></li>
            <li><a href="<?php echo $this->url('linuxstatus',array('action' => 'processes'));?>">Processes</a></li>
        </ul>
    </div>
    <div class="right">
        <span>Information</span>
        <ul>
           <li class="li"><p class="l7">TYPE</p><p class="l7">USER</p><p class="l7">HOME</p></li>
           <?php for($i=0;$i<count($data);$i++){?>
           <li class="li"><p class="l7"><?php echo $data[$i][0];?></p><p class="l7"><?php echo $data[$i][1];?></p><p class="l7"><?php echo $data[$i][2];?></p></li>
           <?php } unset($data); ?> 
        </ul>
    </div>
</div>