<div class="content">
    <div class="introduce">About me</div>
    <div class="wh4">
        <div class="whbg">
            <div class="what">
                <div class="whatlogo">Why</div>
                <div class="whattxt">
                    With the rapid development of the Internent industry and information technology ,the MySQL database management system has being widely used in the opening  
                    of Internet by small and medium-sized websites, thanks to its small volume, quick speed, low cost as well as opening source. Therefore, it is very important 
                    to monitor the MySQL database management system and to ensure the normal operation and data security.
                </div>
            </div>
            <div class="what">
                <div class="whatlogo">What</div>
                <div class="whattxt">
                    MySQL Smart Tools is a developed by shell + PHP open source MySQL server intelligent management Tools,As in ordinary individual users and small and medium-
                    sized enterprises, adopted by the industry known as the "LAMP" combination, Linux as the operating system, Apache as the Web server, MySQL as the database, 
                    PHP as the server-side script interpreter. It consists of shell implementation data collection, using PHP implementation of Web way show the performance of 
                    the MySQL server status information, only in view of the current development server for condition monitoring and performance analysis, to help small and 
                    medium-sized Internet project developers to intuitive understanding of the running conditions of the MySQL server.
                </div>
            </div>
            <div class="what">
                <div class="whatlogo">Who</div>
                <div class="whattxt">
                    The Open Research Platform on Information technology Of HACTCM is relying on the construction of Henan Unitersity of Traditional Chinese Medicine College of 
                    Information Technology, Composed in the Internet industry, software industry team of teachers and student team, to study the Internet application technology 
                    and the teaching and research for the purpose of academic research institutions, the main research direction is the teaching reform, the application of Web 
                    standards, computer networks, software development, etc.
                </div>
            </div>
            <div class="what" id="where">
                <div class="whatlogo">Where</div>
                <div class="whattxt">
                    <p>http://open.hactcm.edu.cn</p>
                    <p>China, Henan province, Zhengzhou city, Jinshui and Boxue crossroads</p>
                    <p>Henan Unitersity of Traditional Chinese Medicine teaching experiment building BN511 (The Open Research Platform on Information technology Of HACTCM)</p>
                </div>
                <div id='dituContent'></div>  
            </div>
        </div> 
        <div class="mgnbtm"></div>
    </div>
</div>


