<?php echo "<script type='text/javascript'>deleteview='" . $this->url('views',array('action' => 'deleteview')) . "'</script>" ?>
<div class="content">
    <div class="left">
        <span>Management</span>
        <ul>
            <li><a href="<?php echo $this->url('database',array('action' => 'index'))?>">DataBase</a></li>
            <li class="current"><a href="<?php echo $this->url('views',array('action' => 'index'))?>">Views</a></li>
            <li><a href="<?php echo $this->url('triggers',array('action' => 'index'))?>">Triggers</a></li>
            <li><a href="<?php echo $this->url('user',array('action' => 'index'))?>">User</a></li>
            <li><a href="<?php echo $this->url('sqloperation', array('action' => 'index'));?>">SQL Operation</a></li>
        </ul>
    </div>
    <div class="right">
        <span>Views&nbsp;&nbsp;<a href="<?php echo $this->url('views',array('action' => 'createview')) ?>" style="align: right;">Create View</a></span>
        <ul>
            <li class="li">
                <p class="l2">DB</p><p class="l8">ViewName</p>
                <p class="l8">Definition</p><p class="l9">Option</p>
                <p class="l2">Updatable</p><p class="l4">Definer</p>
                <p class="l8">Security</p><p class="l2">Operate</p>
            </li>
            <?php 
            if(!mysql_num_rows($result)){
                echo 'This is not exists views !';
            }else{
                $i=1;
                while ($row = mysql_fetch_array($result)) {?>
                <li class="li" id="del<?php echo $i;?>">
                        <p class="l2" title="<?php echo $row[1]; ?>"><?php echo $row[1]; ?></p>
                        <p class="l8" title="<?php echo $row[2]; ?>"><?php echo $row[2]; ?></p>
                        <p class="l8" title="<?php echo $row[3]; ?>"><?php echo substr($row[3], 0, 10); ?></p>
                        <p class="l9" title="<?php echo $row[4]; ?>"><?php echo $row[4]; ?></p>
                        <p class="l2" title="<?php echo $row[5]; ?>"><?php echo $row[5]; ?></p>
                        <p class="l4" title="<?php echo $row[6]; ?>"><?php echo $row[6]; ?></p>
                        <p class="l8" title="<?php echo $row[7]; ?>"><?php echo $row[7]; ?></p>
    <!--                    <p class="l2" title="<?php echo $row[8]; ?>"><?php echo $row[8]; ?></p>-->
                        <p class="l2" title="edit"><a href="<?php echo $this->url('views',array('action' => 'editview', 'dbname' => $row[1], 'name' => $row[2])); ?>">edit</a></p>
                        <p class="l2" title="delete"><a href="#" class="delete" id="<?php echo $i;?>" title="<?php echo $row[1]."/".$row[2]."/deleteview";?>">delete</a></p>
                    </li>
                <?php $i++;}} ?>
        </ul>
    </div>
</div>
<div class="dropdialog"></div>