
<script type="text/javascript">
$(function(){
    $('#addcolumn').click(
        function(){    
            var column = $('input[type=text]').parents('tr').first().clone();
            $('#submit').parents('tr').before(column);
        } 
    )     
}
    
    );
</script>
<div class="content">
    <div class="left">
        <span>Management</span>
        <ul>
            <li class="current"><a href="<?php echo $this->url('database',array('action' => 'index'))?>">DataBase</a></li>
            <li><a href="<?php echo $this->url('views',array('action' => 'index'))?>">Views</a></li>
            <li><a href="<?php echo $this->url('triggers',array('action' => 'index'))?>">Triggers</a></li>
            <li><a href="<?php echo $this->url('user',array('action' => 'index'))?> ">User</a></li>
            <li><a href="<?php echo $this->url('sqloperation', array('action' => 'index'));?>">SQL Operation</a></li>
        </ul>
    </div>
    <div class="right">
        <span>Create Table</span>
        <div>
            <form name="form" action="<?php echo $this->url('database', array('action' => 'createtablehandle')); ?>" method="post" >
                <input type="hidden" name="dbname" value="<?php echo $dbname; ?>" />
                <div class="tbname">tablename:<input type="text" name="tablename" />
                    <input id="addcolumn" type="button" name="addcolumn" value="add a column"/></div>
                <table id="table">
                    <tr>
                        <th>name</th>
                        <th>type</th>
                        <th>length</th>
                        <th>default</th>
                        <th>attr</th>
                        <th>index</th>
                    </tr>
                    <tr>
                        <td><input type="text" name="name[]" /></td>
                        <td><input type="text" name="type[]" value="int" /></td>
                        <td><input type="text" name="length[]" /></td>
                        <td><input type="text" name="default[]" /></td>
                        <td><input type="text" name="attr[]" /></td>
                        <td><input type="text" name="index[]" /></td>
                    </tr>
                    <tr>
                        <td><input type="text" name="name[]" /></td>
                        <td><input type="text" name="type[]" value="int" /></td>
                        <td><input type="text" name="length[]" /></td>
                        <td><input type="text" name="default[]" /></td>
                        <td><input type="text" name="attr[]" /></td>
                        <td><input type="text" name="index[]" /></td>
                    </tr>
                    <tr>
                        <td colspan="6"><input type="submit" id="submit" value="Create Table" /></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>

